const ADDPLATFORMS = 'ADDPLATFORMS'
const ADDBROUSER = 'ADDBROUSER'
const OPERATINGSYSTEMS = 'OPERATINGSYSTEMS'
const GROUPS = 'GROUPS'
const ADDSPISOK = 'ADDSPISOK'

export {ADDPLATFORMS, ADDBROUSER, OPERATINGSYSTEMS, GROUPS, ADDSPISOK}
